name:                elm-interop
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/elm-interop#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - text
  - aeson == 1.3.1.1
  - vinyl == 0.8.1.1
  - unordered-containers == 0.2.9.0
  - invariant == 0.5.1
  - recursion-schemes == 5.0.3

library:
  source-dirs: src

executables:
  example:
    main: Example.hs
