name:                elm-interop
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/dhall-elm#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md
ghc-options:
- -j4
- -Werror
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wpartial-fields
- -Wredundant-constraints

library:
  dependencies:
  - aeson
  - base
  - bytestring
  - containers
  - hashable
  - http-types
  - http-media
  - mtl
  - recursion-schemes
  - servant
  - text
  - scientific
  - unordered-containers
  - vector
  - wl-pprint-text
  exposed-modules:
  - Servant.Interop.Elm
  - Servant.Interop
  - Wire
  - Wire.Json
  source-dirs: src

tests:
  spec:
    dependencies:
    - base
    - elm-interop
    - servant
    - tasty
    - tasty-golden
    - text
    main: Main.hs
    source-dirs: tests
