name:                dhall-elm
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/dhall-elm#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base
  - dhall
  - insert-ordered-containers
  - recursion-schemes
  - text

executables:
  dhall-elm:
    source-dirs:      src
    main:             Main.hs
